root = "."
tmp_dir = "tmp"
tmp_dir = "tmp"

[build]
cmd = 'CGO_ENABLED=0 go build -gcflags=all="-N -l" -o tmp/edge ./cmd/server/edge'
full_bin = "dlv exec tmp/edge --listen=127.0.0.1:2345 --headless=true --api-version=2 --accept-multiclient --continue --log --"
bin = "tmp/edge"
include_ext = ["go","json"]
exclude_dir = ["tmp", "vendor"]
pre_cmd = ["jq --arg port \"$EDGE_PORT\" '.buses[0].port = $port' config/edge-config-dev.json > $EDGE_CONFIG_PATH"]
